etika-uk/retailer-integration-guide

_includes/v4/products.md

Product call changes

---

_includes/v4/authentication.md

IP Restricition

---

_includes/v4/products.md
_includes/v4/versioning.md

- Added [Get an Installation](/retailer-integration-guide/api/#installations) call
- Added new field *customer_settlement_fee* to *Product* and *Credit Information*
- Support for *BNPL* products group
[Delivers#94667872]

Customer Settlement Fee

---

_includes/v4/applications_get.md

- Added *Finance* object to *Application*
[Delivers#99500888] 2/2

finance object

---

_includes/v4/applications.md
_includes/v4/applications_get.md
_includes/v4/partial_refunds.md
_includes/v4/settlements.md
_includes/v4/toc.html
_includes/v4/versioning.md
api/index.md

New settlement, cancellation and partial refund calls and changes.
Once merged please update the release date in `_includes/v4/versioning.md`

Settlement calls

---

_data/globals.yml
_includes/v4/authentication.md
_includes/v4/merchant.md
_includes/v4/objects.md
_includes/v4/versioning.md

- Update API URL to correct URL.
- Update several instances of typos and grammar.
- Rewrite a couple of paragraphs to make better sense.
[Delivers#104710490]

Update API Paths , Grammar & Spelling

---

_includes/v4/applications_get.md
index.md

> Review. Put a comment. But don't merge until it will go live.

cancellation fee

---

_includes/v4/applications_get.md

- 'Get an Application' documentation updated
[Delivers #111963201](https://www.pivotaltracker.com/story/show/111963201)

Get application update

---

_includes/v3/welcome.md
index.md

- Changed all instances of merchant.support@paybreak.com to retailer@paybreak.com
[Delivers#112155187](https://www.pivotaltracker.com/story/show/112155187)

Changed the retailer's enquiries email

---

.gitignore
_includes/v4/objects.md

- Added information on `pre-population` under the `Applicant` object section
- Added information on valid inputs for the `Applicant` object
[Delivers [#112807885](https://www.pivotaltracker.com/story/show/112807885)]

Pre population

---

_includes/v4/applications.md

- Amend RIG to match new partial refund response types as in ticket: 
[Pull Request](https://github.com/PayBreak/merchant-api/pull/55)
[Ticket#112988139](https://www.pivotaltracker.com/story/show/112988139)

Doc Updates

---

_includes/v4/applications.md

- Correct quotes around int type

Type Correction

---

index.md

- Add logo section
- Amend some spelling mistakes

Update logo section & spelling / grammar

---

_includes/v4/notifications.md

- Add information regarding non-default parsing of raw POST data

Update notification section

---

_includes/v4/objects.md

- Added documentation to show `date_of_birth` on `Applicant` object

Retailer feedback

---

_includes/v4/applications.md
_includes/v4/applications_credit_info.md
_includes/v4/toc.html

- Added `getCreditInformation` documentation for an `Application`

Credit info

---

_includes/toc.html
_includes/v4/notifications.md
index.md

- Improved Notifications description

Notifications

---

_includes/v4/applications.md
_includes/v4/toc.html

merchant payments changes

---

index.md

Fixed Return URL

---

_includes/v4/response_format.md
_includes/v4/settlements.md
_includes/v4/toc.html
api/index.md

- Adding aggregate settlement api information 
- Adding csv response formatting information
[Delivers #130356905](https://www.pivotaltracker.com/story/show/130356905)

Aggregate settlement api update

---

_includes/v4/products.md
_includes/v4/toc.html

- `Set Product Order` API documentation
[Delivers #132143811](https://www.pivotaltracker.com/story/show/132143811)

Products set order documentation

---

_includes/v4/notifications.md
_includes/v4/system.md
_includes/v4/toc.html
api/index.md

- Added endpoint to retrieve notification server IP's (#139833189)
[Delivers [#139833189](https://www.pivotaltracker.com/story/show/139833189)]
For https://github.com/PayBreak/merchant-api/pull/82

Notification IP Endpoint

---

_includes/v4/notifications.md

- Update link path to new API Call for notification IP’s

Fix Link Path

---

_includes/toc.html
_includes/v4/applications_credit_info.md
_includes/v4/glossary.md
_includes/v4/merchant.md
_includes/v4/objects.md
_includes/v4/partial_refunds.md
_includes/v4/products.md
_includes/v4/settlements.md
_includes/v4/system.md
_includes/v4/toc.html
_includes/v4/upgrade_guide.md
api/index.md
index.md

Improvements to docs

---

_includes/v4/applications.md
_includes/v4/applications_get.md
_includes/v4/toc.html

- Added the new pdf endpoints
- Added the new application property
[Delivers: [#139542975](https://www.pivotaltracker.com/story/show/139542975)]

Agreement dl

---

index.md

- Updating information concerning Paybreak notifications in the *integration checklist* section. (147827757)
[Delivers #147827757](https://www.pivotaltracker.com/story/show/147827757)

Integration Guide Update

---

_includes/v4/dictionaries.md
_includes/v4/installations.md
_includes/v4/toc.html
api/index.md

- Pre-approval documentation
- Dictionaries documentation

Documentation

---

_includes/v4/customer-intelligence.md
_includes/v4/toc.html

- Customer Intelligence section with details about the pre application apis (156370900)
[Delivers [#156370900](https://www.pivotaltracker.com/story/show/156370900)]

Pre application apis #2

---

_includes/v3/overview.md
_includes/v4/customer-intelligence.md
index.md

- information on customer’s test birthday

Add test data info

---

_includes/v4/settlements.md
_includes/v4/toc.html

- Get aggregate Settlement Reports for period details (156502490)
[Delivers [#156502490](https://www.pivotaltracker.com/story/show/156502490)]

Get aggregate Settlement Reports for period description

---

_includes/v4/installations.md
_includes/v4/toc.html

Batch payments

---

_includes/v4/customer-intelligence.md

- Lead score description to match implementation (#160168441)
[Delivers [#160168441](https://www.pivotaltracker.com/story/show/160168441)]
:hand: Wait until implementation hits Test/Live environments.

Add new properties - Lead Score

---

_includes/v4/applications_get.md
_includes/v4/applications_initialize.md

- Lead score on applications (#160168501)
[Delivers [#160168501](https://www.pivotaltracker.com/story/show/160168501)]
:hand: Wait until implementation hits Test/Live environments.

Init with lead score

---

_includes/v4/applications_initialize.md
_includes/v4/objects.md
_includes/v4/toc.html

- documentation for pre_approval (#160613772)
- customer intelligence object (#160613772)
- add email address validation (#161087428)
[Delivers [#160613772](https://www.pivotaltracker.com/story/show/160613772), [#161087428](https://www.pivotaltracker.com/story/show/161087428)]

Add customer intelligence object

---

_includes/v4/customer-intelligence.md

- PreApplication description to match implementation (#160613665)
[Delivesr [#160613665](https://www.pivotaltracker.com/story/show/160613665)]

Add new properties - PreApplication

---

_includes/v4/customer-intelligence.md
_includes/v4/toc.html

- Beta Product Suitability Documentation ([#478](https://gitlab.com/paybreak/work-planner---development-team/-/issues/478))
(minor)

Proroduct suitability documentation

---

_includes/v4/applications_headless.md
_includes/v4/objects.md

- Added Declarations Objected.
- `default` product description to prevent further confusion.

Doc Changes

---

_includes/v4/objects.md

Headless app doc changes
